[2022-12-04 03:05:25,342] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-10-27T08:10:00+00:00 [queued]>
[2022-12-04 03:05:25,385] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-10-27T08:10:00+00:00 [queued]>
[2022-12-04 03:05:25,391] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 03:05:25,392] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 03:05:25,394] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 03:05:25,456] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-10-27 08:10:00+00:00
[2022-12-04 03:05:25,481] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'get_data', 'scheduled__2022-10-27T08:10:00+00:00', '--job-id', '803', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpwe59hkfz', '--error-file', '/tmp/tmpm3k2lh8e']
[2022-12-04 03:05:25,514] {standard_task_runner.py:77} INFO - Job 803: Subtask get_data
[2022-12-04 03:05:25,474] {standard_task_runner.py:52} INFO - Started process 1355 to run task
[2022-12-04 03:05:25,705] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.get_data scheduled__2022-10-27T08:10:00+00:00 [running]> on host 422c372562ce
[2022-12-04 03:05:25,966] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T08:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-27T08:10:00+00:00
[2022-12-04 03:05:26,784] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 03:05:27,643] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=get_data, execution_date=20221027T081000, start_date=20221204T030525, end_date=20221204T030527
[2022-12-04 03:05:27,810] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 03:05:28,004] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
