[2022-12-04 03:00:01,564] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-10-27T06:50:00+00:00 [queued]>
[2022-12-04 03:00:01,784] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-10-27T06:50:00+00:00 [queued]>
[2022-12-04 03:00:01,794] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 03:00:01,799] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 03:00:01,799] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 03:00:01,896] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-10-27 06:50:00+00:00
[2022-12-04 03:00:01,921] {standard_task_runner.py:52} INFO - Started process 1014 to run task
[2022-12-04 03:00:02,051] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'get_data', 'scheduled__2022-10-27T06:50:00+00:00', '--job-id', '757', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpk4q02a2x', '--error-file', '/tmp/tmpvzmpob_2']
[2022-12-04 03:00:02,077] {standard_task_runner.py:77} INFO - Job 757: Subtask get_data
[2022-12-04 03:00:02,481] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.get_data scheduled__2022-10-27T06:50:00+00:00 [running]> on host 422c372562ce
[2022-12-04 03:00:02,885] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T06:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-27T06:50:00+00:00
[2022-12-04 03:00:03,605] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 03:00:03,760] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=get_data, execution_date=20221027T065000, start_date=20221204T030001, end_date=20221204T030003
[2022-12-04 03:00:03,858] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 03:00:04,008] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
