[2022-12-04 17:35:48,606] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-11-10T11:30:00+00:00 [queued]>
[2022-12-04 17:35:48,644] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-11-10T11:30:00+00:00 [queued]>
[2022-12-04 17:35:48,646] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:35:48,646] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 17:35:48,647] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:35:48,679] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-11-10 11:30:00+00:00
[2022-12-04 17:35:48,687] {standard_task_runner.py:52} INFO - Started process 19094 to run task
[2022-12-04 17:35:48,692] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-11-10T11:30:00+00:00', '--job-id', '10695', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmp_p19a4vn', '--error-file', '/tmp/tmptk82eb8y']
[2022-12-04 17:35:48,693] {standard_task_runner.py:77} INFO - Job 10695: Subtask save_to_csv
[2022-12-04 17:35:48,790] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-11-10T11:30:00+00:00 [running]> on host 7a020590adae
[2022-12-04 17:35:48,902] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-11-10T11:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-10T11:30:00+00:00
[2022-12-04 17:35:48,975] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 17:35:49,007] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221110T113000, start_date=20221204T173548, end_date=20221204T173549
[2022-12-04 17:35:49,079] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 17:35:49,158] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
