[2022-12-04 03:21:02,507] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-27T15:20:00+00:00 [queued]>
[2022-12-04 03:21:02,522] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-27T15:20:00+00:00 [queued]>
[2022-12-04 03:21:02,522] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 03:21:02,523] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 03:21:02,523] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 03:21:02,556] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-10-27 15:20:00+00:00
[2022-12-04 03:21:02,562] {standard_task_runner.py:52} INFO - Started process 2421 to run task
[2022-12-04 03:21:02,567] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-10-27T15:20:00+00:00', '--job-id', '968', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpax75lh5n', '--error-file', '/tmp/tmp09zqqx_l']
[2022-12-04 03:21:02,568] {standard_task_runner.py:77} INFO - Job 968: Subtask save_to_csv
[2022-12-04 03:21:02,664] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-10-27T15:20:00+00:00 [running]> on host 422c372562ce
[2022-12-04 03:21:02,821] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T15:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-27T15:20:00+00:00
[2022-12-04 03:21:02,907] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 03:21:02,922] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221027T152000, start_date=20221204T032102, end_date=20221204T032102
[2022-12-04 03:21:02,956] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 03:21:03,003] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
