[2022-12-04 17:21:08,820] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.delete_local_file scheduled__2022-11-10T04:40:00+00:00 [queued]>
[2022-12-04 17:21:08,965] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.delete_local_file scheduled__2022-11-10T04:40:00+00:00 [queued]>
[2022-12-04 17:21:08,976] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:21:09,009] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 17:21:09,041] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:21:09,222] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): delete_local_file> on 2022-11-10 04:40:00+00:00
[2022-12-04 17:21:09,288] {standard_task_runner.py:52} INFO - Started process 17838 to run task
[2022-12-04 17:21:09,289] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'delete_local_file', 'scheduled__2022-11-10T04:40:00+00:00', '--job-id', '10433', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpk2u6elng', '--error-file', '/tmp/tmp10ylnz8a']
[2022-12-04 17:21:09,355] {standard_task_runner.py:77} INFO - Job 10433: Subtask delete_local_file
[2022-12-04 17:21:10,358] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.delete_local_file scheduled__2022-11-10T04:40:00+00:00 [running]> on host 7a020590adae
[2022-12-04 17:21:11,163] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=delete_local_file
AIRFLOW_CTX_EXECUTION_DATE=2022-11-10T04:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-10T04:40:00+00:00
[2022-12-04 17:21:11,171] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 17:21:12,466] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=delete_local_file, execution_date=20221110T044000, start_date=20221204T172108, end_date=20221204T172112
[2022-12-04 17:21:12,755] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 17:21:13,139] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
