[2022-12-04 17:39:35,016] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-11-10T13:10:00+00:00 [queued]>
[2022-12-04 17:39:35,029] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-11-10T13:10:00+00:00 [queued]>
[2022-12-04 17:39:35,030] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:39:35,030] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 17:39:35,031] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:39:35,046] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-11-10 13:10:00+00:00
[2022-12-04 17:39:35,052] {standard_task_runner.py:52} INFO - Started process 19416 to run task
[2022-12-04 17:39:35,057] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-11-10T13:10:00+00:00', '--job-id', '10756', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpbyoghgha', '--error-file', '/tmp/tmpt0coqrji']
[2022-12-04 17:39:35,058] {standard_task_runner.py:77} INFO - Job 10756: Subtask save_to_csv
[2022-12-04 17:39:35,193] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-11-10T13:10:00+00:00 [running]> on host 7a020590adae
[2022-12-04 17:39:35,280] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-11-10T13:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-10T13:10:00+00:00
[2022-12-04 17:39:35,320] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 17:39:35,335] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221110T131000, start_date=20221204T173935, end_date=20221204T173935
[2022-12-04 17:39:35,390] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 17:39:35,441] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
