[2022-12-04 05:16:32,120] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-29T09:00:00+00:00 [queued]>
[2022-12-04 05:16:32,166] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-29T09:00:00+00:00 [queued]>
[2022-12-04 05:16:32,167] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 05:16:32,167] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 05:16:32,168] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 05:16:32,239] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-10-29 09:00:00+00:00
[2022-12-04 05:16:32,250] {standard_task_runner.py:52} INFO - Started process 8078 to run task
[2022-12-04 05:16:32,257] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-10-29T09:00:00+00:00', '--job-id', '1968', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpc5wnoky2', '--error-file', '/tmp/tmpzzlq12rb']
[2022-12-04 05:16:32,275] {standard_task_runner.py:77} INFO - Job 1968: Subtask save_to_csv
[2022-12-04 05:16:32,528] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-10-29T09:00:00+00:00 [running]> on host 422c372562ce
[2022-12-04 05:16:32,805] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-10-29T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-29T09:00:00+00:00
[2022-12-04 05:16:32,947] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 05:16:33,390] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221029T090000, start_date=20221204T051632, end_date=20221204T051633
[2022-12-04 05:16:33,480] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 05:16:33,610] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
