[2022-12-03 14:08:56,131] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-10-26T05:30:00+00:00 [queued]>
[2022-12-03 14:08:56,195] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-10-26T05:30:00+00:00 [queued]>
[2022-12-03 14:08:56,200] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 14:08:56,206] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-03 14:08:56,207] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 14:08:56,288] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-10-26 05:30:00+00:00
[2022-12-03 14:08:56,294] {standard_task_runner.py:52} INFO - Started process 186 to run task
[2022-12-03 14:08:56,330] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'get_data', 'scheduled__2022-10-26T05:30:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpgxcl33sk', '--error-file', '/tmp/tmpfmy77i91']
[2022-12-03 14:08:56,332] {standard_task_runner.py:77} INFO - Job 120: Subtask get_data
[2022-12-03 14:08:56,531] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.get_data scheduled__2022-10-26T05:30:00+00:00 [running]> on host 422c372562ce
[2022-12-03 14:08:56,896] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T05:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-26T05:30:00+00:00
[2022-12-03 14:08:57,824] {python.py:175} INFO - Done. Returned value was: None
[2022-12-03 14:08:58,051] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=get_data, execution_date=20221026T053000, start_date=20221203T140856, end_date=20221203T140858
[2022-12-03 14:08:58,371] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-03 14:08:58,766] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
