[2022-12-04 11:03:07,930] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-11-03T22:40:00+00:00 [queued]>
[2022-12-04 11:03:09,564] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-11-03T22:40:00+00:00 [queued]>
[2022-12-04 11:03:09,573] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 11:03:09,583] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 11:03:09,584] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 11:03:09,683] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-11-03 22:40:00+00:00
[2022-12-04 11:03:09,692] {standard_task_runner.py:52} INFO - Started process 12041 to run task
[2022-12-04 11:03:09,732] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'get_data', 'scheduled__2022-11-03T22:40:00+00:00', '--job-id', '5067', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmp3kwn0trr', '--error-file', '/tmp/tmpo_wkc4kp']
[2022-12-04 11:03:09,760] {standard_task_runner.py:77} INFO - Job 5067: Subtask get_data
[2022-12-04 11:03:10,484] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.get_data scheduled__2022-11-03T22:40:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 11:03:10,885] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T22:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T22:40:00+00:00
[2022-12-04 11:03:11,695] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 11:03:12,839] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=get_data, execution_date=20221103T224000, start_date=20221204T110307, end_date=20221204T110312
[2022-12-04 11:03:13,055] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 11:03:13,773] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
