[2022-12-04 10:44:04,252] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-11-01T21:40:00+00:00 [queued]>
[2022-12-04 10:44:04,273] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-11-01T21:40:00+00:00 [queued]>
[2022-12-04 10:44:04,274] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:44:04,274] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 10:44:04,275] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:44:04,316] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-11-01 21:40:00+00:00
[2022-12-04 10:44:04,322] {standard_task_runner.py:52} INFO - Started process 7904 to run task
[2022-12-04 10:44:04,331] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'get_data', 'scheduled__2022-11-01T21:40:00+00:00', '--job-id', '3876', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmp4pwwne5u', '--error-file', '/tmp/tmp7n_6np27']
[2022-12-04 10:44:04,336] {standard_task_runner.py:77} INFO - Job 3876: Subtask get_data
[2022-12-04 10:44:04,705] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.get_data scheduled__2022-11-01T21:40:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 10:44:06,400] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T21:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T21:40:00+00:00
[2022-12-04 10:44:07,508] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 10:44:07,799] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=get_data, execution_date=20221101T214000, start_date=20221204T104404, end_date=20221204T104407
[2022-12-04 10:44:07,956] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 10:44:08,246] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
