[2022-12-04 12:52:26,245] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-11-06T10:50:00+00:00 [queued]>
[2022-12-04 12:52:26,331] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-11-06T10:50:00+00:00 [queued]>
[2022-12-04 12:52:26,333] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 12:52:26,339] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 12:52:26,347] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 12:52:26,462] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-11-06 10:50:00+00:00
[2022-12-04 12:52:26,500] {standard_task_runner.py:52} INFO - Started process 1321 to run task
[2022-12-04 12:52:26,540] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'get_data', 'scheduled__2022-11-06T10:50:00+00:00', '--job-id', '6977', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpkjr_zh5v', '--error-file', '/tmp/tmpn30z5dvn']
[2022-12-04 12:52:26,543] {standard_task_runner.py:77} INFO - Job 6977: Subtask get_data
[2022-12-04 12:52:26,973] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.get_data scheduled__2022-11-06T10:50:00+00:00 [running]> on host 7a020590adae
[2022-12-04 12:52:27,509] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-06T10:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-06T10:50:00+00:00
[2022-12-04 12:52:28,377] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 12:52:28,461] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=get_data, execution_date=20221106T105000, start_date=20221204T125226, end_date=20221204T125228
[2022-12-04 12:52:28,821] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 12:52:29,049] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
