[2022-12-04 10:09:35,152] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-10-31T07:50:00+00:00 [queued]>
[2022-12-04 10:09:35,197] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-10-31T07:50:00+00:00 [queued]>
[2022-12-04 10:09:35,212] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:09:35,214] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 10:09:35,215] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 10:09:35,326] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-10-31 07:50:00+00:00
[2022-12-04 10:09:35,367] {standard_task_runner.py:52} INFO - Started process 3963 to run task
[2022-12-04 10:09:35,430] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'get_data', 'scheduled__2022-10-31T07:50:00+00:00', '--job-id', '2938', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmp3wg3dqih', '--error-file', '/tmp/tmpyboeoerh']
[2022-12-04 10:09:35,449] {standard_task_runner.py:77} INFO - Job 2938: Subtask get_data
[2022-12-04 10:09:36,308] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.get_data scheduled__2022-10-31T07:50:00+00:00 [running]> on host 9e44869ff3ef
[2022-12-04 10:09:37,317] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T07:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T07:50:00+00:00
[2022-12-04 10:09:39,271] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 10:09:39,875] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=get_data, execution_date=20221031T075000, start_date=20221204T100935, end_date=20221204T100939
[2022-12-04 10:09:39,988] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 10:09:40,241] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
