[2022-12-03 17:53:15,691] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-26T15:20:00+00:00 [queued]>
[2022-12-03 17:53:15,788] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.save_to_csv scheduled__2022-10-26T15:20:00+00:00 [queued]>
[2022-12-03 17:53:15,791] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 17:53:15,793] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-03 17:53:15,797] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-03 17:53:15,835] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_to_csv> on 2022-10-26 15:20:00+00:00
[2022-12-03 17:53:15,845] {standard_task_runner.py:52} INFO - Started process 967 to run task
[2022-12-03 17:53:15,863] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'save_to_csv', 'scheduled__2022-10-26T15:20:00+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmpuxgqv2fl', '--error-file', '/tmp/tmp1th40yef']
[2022-12-03 17:53:15,865] {standard_task_runner.py:77} INFO - Job 378: Subtask save_to_csv
[2022-12-03 17:53:16,120] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.save_to_csv scheduled__2022-10-26T15:20:00+00:00 [running]> on host 422c372562ce
[2022-12-03 17:53:16,487] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=save_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T15:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-26T15:20:00+00:00
[2022-12-03 17:53:16,698] {python.py:175} INFO - Done. Returned value was: None
[2022-12-03 17:53:17,008] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=save_to_csv, execution_date=20221026T152000, start_date=20221203T175315, end_date=20221203T175317
[2022-12-03 17:53:17,203] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-03 17:53:17,319] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
