[2022-12-04 15:09:24,271] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-11-09T06:30:00+00:00 [queued]>
[2022-12-04 15:09:24,292] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-11-09T06:30:00+00:00 [queued]>
[2022-12-04 15:09:24,293] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 15:09:24,293] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 15:09:24,294] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 15:09:24,311] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-11-09 06:30:00+00:00
[2022-12-04 15:09:24,317] {standard_task_runner.py:52} INFO - Started process 13768 to run task
[2022-12-04 15:09:24,323] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'get_data', 'scheduled__2022-11-09T06:30:00+00:00', '--job-id', '9589', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmp1_4a6yf0', '--error-file', '/tmp/tmprhr_1f9r']
[2022-12-04 15:09:24,325] {standard_task_runner.py:77} INFO - Job 9589: Subtask get_data
[2022-12-04 15:09:24,409] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.get_data scheduled__2022-11-09T06:30:00+00:00 [running]> on host 7a020590adae
[2022-12-04 15:09:24,482] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-09T06:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-09T06:30:00+00:00
[2022-12-04 15:09:25,134] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 15:09:25,148] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=get_data, execution_date=20221109T063000, start_date=20221204T150924, end_date=20221204T150925
[2022-12-04 15:09:25,177] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 15:09:25,233] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
